# Generated by Django 2.2.7 on 2019-11-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passangerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passanger',
            old_name='id',
            new_name='pid',
        ),
    ]
